### ISSUE TITLE
Error while running ./run.py

### ISSUE THREAD

**Issue by WenXinDong2018** [powerhouseofthecell/machine_feeling#2]
I am getting the following error and I don't know which part of the code I should change. 

ValueError: Error when checking target: expected dense_2 to have shape (None, 2) but got array with shape (9, 3)

Can someone help me?

**Comment by daemonprocess404** [comment]
Same problem. Try:
`./run.py --pretrained`

This runs fine, however, is not the solution for the ValueError.

**Comment by WenXinDong2018** [comment]
Problem Solved by replacing 

`model.add(Dense(16, activation='relu'),input_shape=(None,3))
`
with

`            model.add(Dense(16, activation='relu'))
`
